[2024-08-03T22:27:24.299+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T22:27:24.350+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.run_extraction manual__2024-08-03T22:27:21.069092+00:00 [queued]>
[2024-08-03T22:27:24.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.run_extraction manual__2024-08-03T22:27:21.069092+00:00 [queued]>
[2024-08-03T22:27:24.359+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-03T22:27:24.373+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_extraction> on 2024-08-03 22:27:21.069092+00:00
[2024-08-03T22:27:24.379+0000] {standard_task_runner.py:64} INFO - Started process 230 to run task
[2024-08-03T22:27:24.382+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'run_extraction', 'manual__2024-08-03T22:27:21.069092+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpkhdls53m']
[2024-08-03T22:27:24.388+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask run_extraction
[2024-08-03T22:27:24.463+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.run_extraction manual__2024-08-03T22:27:21.069092+00:00 [running]> on host bd1346cccc16
[2024-08-03T22:27:24.558+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='run_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T22:27:21.069092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-03T22:27:21.069092+00:00'
[2024-08-03T22:27:24.559+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T22:27:24.580+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-03T22:27:24.581+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python usr/local/airflow/src/extraction.py']
[2024-08-03T22:27:24.617+0000] {subprocess.py:86} INFO - Output:
[2024-08-03T22:27:24.684+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/airflowtmpidc9zsde/usr/local/airflow/src/extraction.py': [Errno 2] No such file or directory
[2024-08-03T22:27:24.687+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-03T22:27:24.688+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T22:27:24.698+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-03T22:27:24.705+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=run_extraction, run_id=manual__2024-08-03T22:27:21.069092+00:00, execution_date=20240803T222721, start_date=20240803T222724, end_date=20240803T222724
[2024-08-03T22:27:24.723+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task run_extraction (Bash command failed. The command returned a non-zero exit code 2.; 230)
[2024-08-03T22:27:24.760+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-03T22:27:24.777+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T22:27:24.794+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
